title : Chukwudi Peter Kubiat Jones 
logo: WhatsApp Image 2025-07-23 at 16.21.48_938b1e80.jpg
theme: jekyll-theme-cayman
cayman:
  header_bg: "#6a11cb" # Purple gradient
  section_bg: "#f5f7fa" # Light gray
